### ISSUE TITLE
[BUG]"unknown service xxx" when use native grpc client to call go-micro grpc server? 

### ISSUE THREAD

**Issue by seaguest** [micro/go-micro#2210]
**Describe the bug**
I have a go-micro grpc service, then I build standard grpc client (not the plugin grpc client) based on the proto file, I got the following error  when I tried to call the service with the standard grpc client.:
```
client/client.go:31: could not greet: rpc error: code = Unimplemented desc = unknown service xxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13ef83f]

goroutine 1 [running]:
main.main()
	/Users/xxx/Git/grpc-demo/client/client.go:33 +0x2ff
```

**To Reproduce**
The reason not to use the plugin grpc client (this works) is because I want to make mobile phones interact with server using grpc, and I use envoy-grpc as the loadbalancer.

Here is the go-micro server code:
```
	reg := etcd.NewRegistry(func(op *registry.Options) {
		op.Addrs = []string{
			"127.0.0.1:2379",
		}
	})
	service := micro.NewService(
		micro.Server(grpc.NewServer(s.Address(":8001"), s.Name("cms"))),
		micro.Registry(reg),
	)

	cms.RegisterCmsHandler(service.Server(), &server.CmsService{})
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
```

the native grpc client:
```
	conn, err := grpc.Dial("localhost:8001", grpc.WithInsecure(), grpc.WithBlock())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := cms.NewCmsClient(conn)

	// Contact the server and print out its response.
	name := "hello"
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	r, err := c.Call(ctx, &cms.Request{Name: name})
	if err != nil {
		log.Errorf("could not greet: %v", err)
	}
```

**Expected behavior**
grpc call should ssucceed

**Desktop (please complete the following information):**
macos
go-micro 3.5.2.
go 1.16.7

**Comment by seaguest** [comment]
I am not sure if this is due to the grpc version?
I am using 1.40.0 in grpc client, while go-micro uses 1.26.0

**Comment by seaguest** [comment]
I updated the grpc version to 1.40.0
and updated "github.com/asim/go-micro/plugins/registry/etcd/v3" to latest
then problem solved.
