### ISSUE TITLE
concurrent map writes without proper locking

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#318]
```go
2018/10/29 15:48:44 run service map[string]micro.Service{"org.unistack.central.oauth":(*micro.service)(0xc0002680f0), "org.unistack.cent
ral.account":(*micro.service)(0xc000268000)}
2018/10/29 15:48:44 run service org.unistack.central.account
2018/10/29 15:48:44 run service org.unistack.central.oauth
2018/10/29 15:48:44 run service api
2018/10/29 15:48:44 Listening on [::]:7777
2018/10/29 15:48:44 Listening on _INBOX.570fUFJQSXV9yu1Q2SqJ6m
2018/10/29 15:48:44 Listening on _INBOX.570fUFJQSXV9yu1Q2SqJ7O
fatal error: concurrent map writes
2018/10/29 15:48:44 Registering node: org.unistack.central.oauth-f87b3706-db78-11e8-930a-80000208fe80

goroutine 41 [running]:
runtime.throw(0xcdae5d, 0x15)
        /var/home/vtolstov/go/src/runtime/panic.go:608 +0x72 fp=0xc0000ed978 sp=0xc0000ed948 pc=0x433002
runtime.mapassign_faststr(0xbda060, 0xc0001c6090, 0xcd17b9, 0x9, 0x1)
        /var/home/vtolstov/go/src/runtime/map_faststr.go:275 +0x3bf fp=0xc0000ed9e0 sp=0xc0000ed978 pc=0x41984f
github.com/micro/go-micro/server.(*rpcServer).Register(0xc000100500, 0x0, 0x0)
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:231 +0x272 fp=0xc0000ede78 sp=0xc0000ed9e0 pc=0x887ec2
github.com/micro/go-micro.(*service).Start(0xc0002680f0, 0x0, 0x0)
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:122 +0xc8 fp=0xc0000edec0 sp=0xc0000ede78 pc=0x98f718
github.com/micro/go-micro.(*service).Run(0xc0002680f0, 0x0, 0x0)
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:162 +0x40 fp=0xc0000edf90 sp=0xc0000edec0 pc=0x98f9d0
main.runService(0xda21a0, 0xc0002680f0, 0xc00025df20)
        /home/vtolstov/devel/projects/centralv2/main.go:128 +0x31 fp=0xc0000edfc8 sp=0xc0000edf90 pc=0xa87c81
runtime.goexit()
        /var/home/vtolstov/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000edfd0 sp=0xc0000edfc8 pc=0x462be1
created by main.main
        /home/vtolstov/devel/projects/centralv2/main.go:105 +0x38c
```

bug hitting when try to run many services in parallel. Like having slice of micro.Service and
```go
for _, s := range services {
go srvRun(s)
}

func srvRun(s micro.Service) {
s.Run()
}
```

workaround now - simple wait 1 second after each service run.

**Comment by asim** [comment]
Something that could likely be easily fixed but goes back to the part about us only running one service per process.

**Comment by vtolstov** [comment]
This bug appears when you have one service per process, if you by mistake concurrent doing service Run() in goroutine

**Comment by asim** [comment]
Service.Run is only supposed to be called once.

**Comment by asim** [comment]
Feel free to PR a fix. I'm on holiday at the moment.

**Comment by asim** [comment]
Can you provide example setup code? I can't replicate this. Can you also provide do `go get -u` to update your dependencies.

**Comment by vtolstov** [comment]
main.go

```go
package main

import (
        "context"
        "flag"
        "log"
        "os"
        "os/signal"
        "syscall"
        "time"

        "github.com/micro/go-micro"
        broker "github.com/micro/go-micro/broker"
        client "github.com/micro/go-micro/client"
        codec "github.com/micro/go-micro/codec/protorpc"
        registry "github.com/micro/go-micro/registry"
        dselector "github.com/micro/go-micro/selector"
        server "github.com/micro/go-micro/server"
        dbroker "github.com/micro/go-plugins/broker/nats"
        dregistry "github.com/micro/go-plugins/registry/nats"
        dtransport "github.com/micro/go-plugins/transport/nats"
        web "github.com/micro/go-web"
        common "unistack.org/centralv2/common"
        snats "unistack.org/centralv2/sidecar/nats"
)

var (
        cctx, cancel = context.WithCancel(context.Background())
        version      = "undefined"
        sidecar      = snats.NewSidecar()
        cbroker      = dbroker.NewBroker()
        cregistry    = dregistry.NewRegistry()
        ctransport   = dtransport.NewTransport()
        cselector    = dselector.NewSelector(
                dselector.Registry(cregistry),
                dselector.SetStrategy(dselector.RoundRobin),
        )
        apiserver  web.Service
        clientOpts = []client.Option{
                client.Transport(ctransport),
                client.Broker(cbroker),
                client.Registry(cregistry),
                client.Codec("application/grpc", codec.NewCodec),
                client.ContentType("application/grpc"),
        }
        serverOpts = []server.Option{
                server.Transport(ctransport),
                server.Broker(cbroker),
                server.Registry(cregistry),
                server.Codec("application/grpc", codec.NewCodec),
                server.Version(version),
                server.Wait(true),
        }
        serviceOpts = &common.Options{
                ServerOpts: serverOpts,
                ClientOpts: clientOpts,
                Context:    cctx,
                Broker:     cbroker,
                Registry:   cregistry,
                Transport:  ctransport,
                Selector:   cselector,
        }
)

func main() {
        flag.Parse()

        chErr := make(chan error)

        nats := snats.NewSidecar()
        err := nats.Start()
        if err != nil {
                log.Fatal(err)
        }

        registry.DefaultRegistry = cregistry
        server.DefaultServer = server.NewServer(serverOpts...)
        broker.DefaultBroker = cbroker
        client.DefaultClient = client.NewClient(clientOpts...)

        client.Broker(cbroker)
        client.Registry(cregistry)
        server.Broker(cbroker)
        server.Registry(cregistry)
        services := common.Services()
        for idx := 0; idx < 100; idx++ {
                go runService(services[0], chErr)
        }

        chSig := make(chan os.Signal)
        signal.Notify(chSig, syscall.SIGTERM, syscall.SIGINT)

        select {
        case <-chSig:
                cancel()
                time.Sleep(1 * time.Second)
                os.Exit(0)
        case err := <-chErr:
                log.Fatal(err)
        }
}

func runService(s micro.Service, chErr chan error) {
        chErr <- s.Run()
}
```

simple service loader:
```go
package main

import (
        "log"

        common "unistack.org/centralv2/common"
        "unistack.org/centralv2/service/oauth"
)

func init() {
        srv, err := oauth.Service(serviceOpts)
        if err != nil {
                log.Fatal(err)
        } else {
                s := srv
                common.RegisterService(s.Server().Options().Name, s)
        }
}
```
service implementation
```go
type OauthServer struct {}

func Service(serviceOpts *service.Options) (micro.Service, error) {
        sopts := serviceOpts.ServerOpts
        sopts = append(sopts, server.Name("org.unistack.central.oauth"))
        copts := serviceOpts.ClientOpts

        srv := micro.NewService(
                micro.Registry(serviceOpts.Registry),
                micro.Broker(serviceOpts.Broker),
                micro.Transport(serviceOpts.Transport),
                micro.Selector(serviceOpts.Selector),
                micro.Server(server.NewServer(sopts...)),
                micro.Client(client.NewClient(copts...)),
                micro.Context(serviceOpts.Context),
        )
        RegisterOauthServiceHandler(srv.Server(), oauthService)
        return srv, nil
}
```

**Comment by vtolstov** [comment]
main thing is :
```
for idx := 0; idx < 100; idx++ {
                go runService(services[0], chErr)
        }
```
in you case 100 may be big or may be small. sometimes i can reproduce issue with 5 iterations, sometimes i need 100. But root case is the same. May be i need to compile with race detector to see more issues like this.

**Comment by asim** [comment]
Yea I'd say compile with race detector to see where the issue is occurring. Its not clear from the current stack trace. It implies some sort of race in access to the transport. Your service initialisation ordering makes it so some things aren't used properly.

```
        srv := micro.NewService(
                micro.Registry(serviceOpts.Registry),
                micro.Broker(serviceOpts.Broker),
                micro.Transport(serviceOpts.Transport),
                micro.Selector(serviceOpts.Selector),
                micro.Server(server.NewServer(sopts...)),
                micro.Client(client.NewClient(copts...)),
                micro.Context(serviceOpts.Context),
        )
```

Initialise Client/Server first. When you replace the client/server, it basically ignores any other internal options previously set. Client and Server encapsulate broker, registry, selector and transport.

**Comment by vtolstov** [comment]
@asim thanks, but what you mean "Initialise Client/Server first"? As i understand this options goes to struct and after that used by service.
Or you mean something like this:
```go
s := server.NewServer(sopts...)
c := client.NewClient(copts...)
srv := micro.NewService(
  micro.Server(s),
  micro.Client(c),
  micro.Context(serviceOpts.Context),
  micro.Selector(serviceOpts.Selector),
)
```

and don't use micro.Registry, micro.Transport, micro.Broker?

**Comment by vtolstov** [comment]
```go
WARNING: DATA RACE
Write at 0x00c0002c6018 by goroutine 32:
  github.com/micro/go-plugins/broker/nats.(*nbroker).Connect()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-plugins/broker/nats/nats.go:106 +0x1fc
  github.com/micro/go-micro/server.(*rpcServer).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:420 +0x4bb
  github.com/micro/go-micro.(*service).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:118 +0x12c
  github.com/micro/go-micro.(*service).Run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:162 +0x50
  main.runService()
      /home/vtolstov/devel/projects/centralv2/main.go:120 +0x3e

Previous read at 0x00c0002c6018 by goroutine 38:
  github.com/micro/go-plugins/broker/nats.(*nbroker).Connect()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-plugins/broker/nats/nats.go:88 +0x61
  github.com/micro/go-micro/server.(*rpcServer).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:420 +0x4bb
  github.com/micro/go-micro.(*service).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:118 +0x12c
  github.com/micro/go-micro.(*service).Run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:162 +0x50
  main.runService()
      /home/vtolstov/devel/projects/centralv2/main.go:120 +0x3e

Goroutine 32 (running) created at:
  main.main()
      /home/vtolstov/devel/projects/centralv2/main.go:96 +0x3d7

Goroutine 38 (running) created at:
  main.main()
      /home/vtolstov/devel/projects/centralv2/main.go:96 +0x3d7
```

**Comment by vtolstov** [comment]
thanks! the issue is fixed
