### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#374]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4fb552]

goroutine 237 [running]:
context.(*valueCtx).Done(0xc000352390, 0xc000585f00)
        <autogenerated>:1 +0x32
github.com/micro/go-micro.(*service).Run(0xc00035a4b0, 0xc000366f50, 0x1)
        /home/vtolstov/.cache/go-path/pkg/mod/github.com/micro/go-micro@v0.17.0/service.go:177 +0x154
unistack.org/centralv2/server.runService(0x165fb40, 0xc00035a4b0, 0xc000337ec0)
        /home/vtolstov/devel/projects/centralv2/server/server.go:69 +0x31
created by unistack.org/centralv2/server.(*Server).Run
        /home/vtolstov/devel/projects/centralv2/server/server.go:47 +0xfb
exit status 2
```

**Comment by vtolstov** [comment]
I don't dig deeper now, but as i understand s.opts.Context is nil.

**Comment by vtolstov** [comment]
context passed to service is:
```
&context.valueCtx{Context:context.Context(nil), key:"api_address", val:"127.0.0.1:12345"}
```

**Comment by vtolstov** [comment]
this is my issue because context is nil, but maybe we need some check ?

**Comment by asim** [comment]
We create a non-nil context here https://github.com/micro/go-micro/blob/461df8d464c9444cbd4b453d0ff5b919a25930b4/options.go#L47. If you're destroying this it's a user error and we're not going to guard against it. Please don't pass a nil context.
