### ISSUE TITLE
panic recovered: interface conversion: struct {} is not proto.Message: missing method ProtoMessage

### ISSUE THREAD

**Issue by wangzhen625** [micro/go-micro#381]
I support a rpc interface for my http gateway, the implemention like 
```
func BindGoogle(ctx context.Context, in *pbuser.BindGoogleReq, out *pbuser.Result) error { 
	result, err := VerifyGoogle(ctx, in.UserId, in.VerifyCode)
	if err != nil {
		...
		return err
	}

	......
}
```

everything is ok except return `err`, it's panic , err is 

```
2019-01-11 17:58:26.373350 I | panic recovered: interface conversion: struct {} is not proto.Message: missing method ProtoMessage
2019-01-11 17:58:26.373520 I | goroutine 57 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xb1
github.com/micro/go-micro/server.(*rpcServer).accept.func1(0x237bbe0, 0xc0005622d0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/server/rpc_server.go:55 +0x133
panic(0x1ff43c0, 0xc000632e40)
	/usr/local/go/src/runtime/panic.go:513 +0x1e6
github.com/micro/go-micro/codec/proto.(*Codec).Write(0xc000030840, 0xc000368050, 0x1fc6720, 0x2ced940, 0x0, 0x0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/codec/proto/proto.go:29 +0x6c
github.com/micro/go-micro/server.(*rpcCodec).Write(0xc0005623c0, 0xc0005adc80, 0x1fc6720, 0x2ced940, 0x20cd101, 0x0, 0x0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/server/rpc_codec.go:133 +0x4bc
github.com/micro/go-micro/server.(*router).sendResponse(0xc000182d80, 0x23711e0, 0xc000262960, 0xc00045e200, 0x1fc6720, 0x2ced940, 0x2379820, 0xc0005623c0, 0xc0002b60f0, 0x46, ...)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/server/rpc_router.go:228 +0x13a
github.com/micro/go-micro/server.(*service).call(0xc0001ac880, 0x2379560, 0xc0005feb40, 0xc000182d80, 0xc000262960, 0xc0002ba240, 0xc00045e200, 0x20de360, 0xc000630bc0, 0x16, ...)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/server/rpc_router.go:268 +0xa8a
github.com/micro/go-micro/server.(*router).ServeRequest(0xc000182d80, 0x2379560, 0xc0005feb40, 0x2379820, 0xc0005623c0, 0xc000337b20, 0x14, 0x0, 0x0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/server/rpc_router.go:343 +0x4a2
github.com/micro/go-micro/server.(*rpcServer).accept(0xc00013c3c0, 0x237bbe0, 0xc0005622d0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/server/rpc_server.go:115 +0x914
github.com/micro/go-micro/server.(*rpcServer).accept-fm(0x237bbe0, 0xc0005622d0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-micro/server/rpc_server.go:405 +0x43
github.com/micro/go-plugins/transport/grpc.(*microTransport).Stream(0xc00045e000, 0x237fe60, 0xc000030700, 0x0, 0x0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-plugins/transport/grpc/handler.go:37 +0x208
github.com/micro/go-plugins/transport/grpc/proto._Transport_Stream_Handler(0x1fcba80, 0xc00045e000, 0x237d580, 0xc0001b8f20, 0x0, 0x0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/go-plugins/transport/grpc/proto/transport.pb.go:127 +0xdc
github.com/micro/grpc-go.(*Server).processStreamingRPC(0xc000312fc0, 0x2382aa0, 0xc000560000, 0xc0003ac400, 0xc0001a7800, 0x2cb7180, 0x0, 0x0, 0x0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/grpc-go/server.go:1154 +0xd82
github.com/micro/grpc-go.(*Server).handleStream(0xc000312fc0, 0x2382aa0, 0xc000560000, 0xc0003ac400, 0x0)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/grpc-go/server.go:1242 +0xa73
github.com/micro/grpc-go.(*Server).serveStreams.func1.1(0xc00018e050, 0xc000312fc0, 0x2382aa0, 0xc000560000, 0xc0003ac400)
	/Users/wangzhen/workspace/gobase/src/github.com/micro/grpc-go/server.go:685 +0xb0
created by github.com/micro/grpc-go.(*Server).serveStreams.func1
	/Users/wangzhen/workspace/gobase/src/github.com/micro/grpc-go/server.go:683 +0xa6
````

now i user 0.17.0 version, but this case not happened in old version 0.13.0.

**Comment by asim** [comment]
What plugins are you using? I see grpc in the stack. Please show me that setup

**Comment by asim** [comment]
The 0.17.0 codec likely has a bug where it attempts to encode the value in the error case. I can't cut a release right now because there are many breaking changes.

**Comment by wangzhen625** [comment]
> The 0.17.0 codec likely has a bug where it attempts to encode the value in the error case. I can't cut a release right now because there are many breaking changes.

ok, i can use the version of 0.16
