### ISSUE TITLE
registry: gossip data race

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#407]
```
==================
WARNING: DATA RACE
Write at 0x00c0005cbbe8 by goroutine 13:
  github.com/micro/go-micro/registry/gossip.addServices()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/util.go:79 +0x244
  github.com/micro/go-micro/registry/gossip.(*gossipRegistry).run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/gossip.go:410 +0x43a

Previous read at 0x00c0005cbbe8 by goroutine 256:
  [failed to restore the stack]

Goroutine 13 (running) created at:
  github.com/micro/go-micro/registry/gossip.NewRegistry()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/gossip.go:608 +0x1e7
  main.(*ucmd).Before()
      /home/vtolstov/devel/projects/centralv2/cmd.go:255 +0x2fbe
  main.(*ucmd).Before-fm()
      /home/vtolstov/devel/projects/centralv2/cmd.go:215 +0x4b
  github.com/micro/cli.(*App).Run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/cli/app.go:184 +0x11cb
  github.com/micro/cli.(*App).RunAndExitOnError()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/cli/app.go:208 +0x70
  main.main()
      /home/vtolstov/devel/projects/centralv2/cmd.go:379 +0x6d
==================
```

**Comment by vtolstov** [comment]
as i'm add debug printfs to this file, line 410 in gossip.go
g.services[u.Service.Name] = addServices(service, []*registry.Service{u.Service})

and util.go
old[i] = s

in function 
func addServices(old, neu []*registry.Service) []*registry.Service {

**Comment by asim** [comment]
Fix has been pushed. Please test and close if resolved.

**Comment by vtolstov** [comment]
works nice without race now

**Comment by vtolstov** [comment]
```
./compute --registry_endpoint 172.16.1.254:4223 --broker_endpoint 172.16.1.254:4222 --registry_address 172.16.1.254:0
2019/02/01 18:48:51 [DEBUG] memberlist: Using dynamic bind port 38687
2019/02/01 18:48:51 [DEBUG] memberlist: Initiating push/pull sync with: 172.16.1.254:4223
2019/02/01 18:48:51 Registry Listening on 172.16.1.254:38687
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc92481]

goroutine 50 [running]:
github.com/micro/go-micro/registry/gossip.addServices(0xc000218200, 0x1, 0x1, 0xc00008ceb0, 0x1, 0x1, 0x1, 0x1, 0x434d58)
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/util.go:81 +0x141
github.com/micro/go-micro/registry/gossip.(*gossipRegistry).run(0xc000250000)
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/gossip.go:426 +0xa72
created by github.com/micro/go-micro/registry/gossip.NewRegistry
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/gossip.go:612 +0x1e8
```

**Comment by vtolstov** [comment]
```
diff --git a/registry/gossip/util.go b/registry/gossip/util.go
index 5e44e375e9ce..0fa8116d1882 100644
--- a/registry/gossip/util.go
+++ b/registry/gossip/util.go
@@ -76,7 +76,7 @@ func addServices(old, neu []*registry.Service) []*registry.Service {
                var seen bool
                for _, o := range old {
                        if o.Version == s.Version {
-                         var sp *registry.Service
+                               sp := new(registry.Service)
                                // make copy
                                *sp = *o
                                // set nodes
```

**Comment by asim** [comment]
Fixed
