### ISSUE TITLE
Panic after registry consul

### ISSUE THREAD

**Issue by GeraltXLi** [micro/go-micro#615]
I write a simple demo which use consul for registry. 
```
package main

import (
	"fmt"
	"microcloud/handler"
	"microcloud/proto/hello"

	"github.com/micro/go-micro"
	"github.com/micro/go-micro/registry"
	"github.com/micro/go-micro/registry/consul"
)

func main() {
	register := consul.NewRegistry(func(options *registry.Options) {
		options.Addrs = []string{
			//"127.0.0.1:8500",
			"127.0.0.1:8500",
		}
	})
	service := micro.NewService(
		micro.Registry(register),
		micro.Name("cloud"))

	service.Init()

	cloudhandler := new(handler.Greeter)
	err := hello.RegisterGreeterHandler(service.Server(),cloudhandler)
	if err != nil {
		fmt.Println(err)
		return
	}

	if err := service.Run();err !=nil{
		fmt.Println(err)
	}
}
```

While there is one node of consul (by using `consul agent -dev`), this demo run success. But it panic when I try to registry it to consul with multiple nodes and I did not use mdns. Also, I can see it registry success in consul. It seems consul with multiple nodes cause this?  Thanks.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f738d]

goroutine 54 [running]:
net.(*conn).ok(...)
        /usr/local/go/src/net/net.go:168
net.(*UDPConn).SyscallConn(...)
        /usr/local/go/src/net/udpsock.go:98
golang.org/x/net/internal/socket.NewConn(0xe51a60, 0x0, 0x0, 0xe51a60, 0x0)
        /mnt/e/gopath/src/golang.org/x/net/internal/socket/rawconn.go:30 +0x9d
golang.org/x/net/ipv6.NewPacketConn(0xe4e9a0, 0x0, 0xe3f3c0)
        /mnt/e/gopath/src/golang.org/x/net/ipv6/endpoint.go:121 +0x5d
github.com/micro/mdns.(*client).setInterface(0xc000192100, 0x0, 0xc000192101, 0x0, 0x0)
        /mnt/e/gopath/src/github.com/micro/mdns/client.go:246 +0x120
github.com/micro/mdns.Listen(0xc0001ea180, 0xc0001e20c0, 0x0, 0x0)
        /mnt/e/gopath/src/github.com/micro/mdns/client.go:108 +0x9f
github.com/micro/go-micro/registry.(*mdnsRegistry).Watch.func1(0xc0001b0180)
        /mnt/e/gopath/src/github.com/micro/go-micro/registry/mdns_registry.go:338 +0x38
created by github.com/micro/go-micro/registry.(*mdnsRegistry).Watch
        /mnt/e/gopath/src/github.com/micro/go-micro/registry/mdns_registry.go:337 +0x129
```

**Comment by milosgajdos** [comment]
There are two things:
* if you use the `consul` registry you need to **explicitly tell micro** you are using it via `MICRO_REGISTRY=consul` environment variable; otherwise `micro` will assume "zeroconf" setup and will attempt to launch `mdns` registry, too (you can see that at the bottom of the trace).
* there is no need to create `registry` object when using `consul` registry, you can point `micro` to it via the `MICRO_REGISTRY` variable as shown above (alternatively you can use `MICRO_REGISTRY_ADDRESS` which points `micro` into a particular endpoint and `micro` will automagically take care of the rest for you.

This is the minimum code you need once you use the `MICRO_REGISTRY` variable:

```Go
func main() {
	service := micro.NewService(
		micro.Name("cloud")),
        )
	service.Init()

	cloudhandler := new(handler.Greeter)
	err := hello.RegisterGreeterHandler(service.Server(),cloudhandler)
	if err != nil {
		fmt.Println(err)
		return
	}

	if err := service.Run();err !=nil{
		fmt.Println(err)
	}
}
```

Then run it something like this:
```shell
MICRO_REGISTRY=consul go run main.go
```

**Comment by GeraltXLi** [comment]
Thank you very much！ I will try it later

**Comment by GeraltXLi** [comment]
Emm....I tried and  it  still  failed . 
`go build -o cloud main.go`
No matter I used `MICRO_REGISTRY=consul ./cloud` or `./cloud --registry consul`.

```
:~$ MICRO_REGISTRY=consul ./cloud
2019/07/29 09:25:00 Transport [http] Listening on 0.0.0.0:32772
2019/07/29 09:25:00 Broker [http] Connected to 0.0.0.0:33408
2019/07/29 09:25:00 Registry [consul] Registering node: cloud-209c90a4-18aa-48a3-b234-caa60e298b48
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f738d]

goroutine 103 [running]:
net.(*conn).ok(...)
        /usr/local/go/src/net/net.go:168
net.(*UDPConn).SyscallConn(...)
        /usr/local/go/src/net/udpsock.go:98
golang.org/x/net/internal/socket.NewConn(0xe51920, 0x0, 0x0, 0xe51920, 0x0)
        /mnt/e/gopath/src/golang.org/x/net/internal/socket/rawconn.go:30 +0x9d
golang.org/x/net/ipv6.NewPacketConn(0xe4e860, 0x0, 0xe3f240)
        /mnt/e/gopath/src/golang.org/x/net/ipv6/endpoint.go:121 +0x5d
github.com/micro/mdns.(*client).setInterface(0xc0001e4080, 0x0, 0xc0001e4001, 0x1460560, 0x7f97d90c7328)
        /mnt/e/gopath/src/github.com/micro/mdns/client.go:246 +0x120
github.com/micro/mdns.Listen(0xc0000c8660, 0xc000200240, 0x0, 0x0)
        /mnt/e/gopath/src/github.com/micro/mdns/client.go:108 +0x9f
github.com/micro/go-micro/registry.(*mdnsRegistry).Watch.func1(0xc00015e570)
        /mnt/e/gopath/src/github.com/micro/go-micro/registry/mdns_registry.go:338 +0x38
created by github.com/micro/go-micro/registry.(*mdnsRegistry).Watch
        /mnt/e/gopath/src/github.com/micro/go-micro/registry/mdns_registry.go:337 +0x129
```

Or
```
:~$ ./cloud --registry consul
2019/07/29 09:26:44 Transport [http] Listening on 0.0.0.0:32815
2019/07/29 09:26:44 Broker [http] Connected to 0.0.0.0:38524
2019/07/29 09:26:44 Registry [consul] Registering node: cloud-5ce05471-59ed-48cf-97de-0bd45ea381c6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f738d]

goroutine 83 [running]:
net.(*conn).ok(...)
        /usr/local/go/src/net/net.go:168
net.(*UDPConn).SyscallConn(...)
        /usr/local/go/src/net/udpsock.go:98
golang.org/x/net/internal/socket.NewConn(0xe51920, 0x0, 0x0, 0xe51920, 0x0)
        /mnt/e/gopath/src/golang.org/x/net/internal/socket/rawconn.go:30 +0x9d
golang.org/x/net/ipv6.NewPacketConn(0xe4e860, 0x0, 0xe3f240)
        /mnt/e/gopath/src/golang.org/x/net/ipv6/endpoint.go:121 +0x5d
github.com/micro/mdns.(*client).setInterface(0xc00025a080, 0x0, 0xc00025a001, 0x0, 0x0)
        /mnt/e/gopath/src/github.com/micro/mdns/client.go:246 +0x120
github.com/micro/mdns.Listen(0xc0000ca660, 0xc0001e2240, 0x0, 0x0)
        /mnt/e/gopath/src/github.com/micro/mdns/client.go:108 +0x9f
github.com/micro/go-micro/registry.(*mdnsRegistry).Watch.func1(0xc00017e870)
        /mnt/e/gopath/src/github.com/micro/go-micro/registry/mdns_registry.go:338 +0x38
created by github.com/micro/go-micro/registry.(*mdnsRegistry).Watch
        /mnt/e/gopath/src/github.com/micro/go-micro/registry/mdns_registry.go:337 +0x129
```

**Comment by asim** [comment]
I think we fire up the use of mdns because of the use of defaults. I've fixed a bug in mdns which should fix this issue related to ipv6. Please do go get -u github.com/micro/go-micro

**Comment by GeraltXLi** [comment]
It worked after I do  go  get  -u github.com/micro/go-micro.
Thank you !
