### ISSUE TITLE
alternative registry backends not working

### ISSUE THREAD

**Issue by HeavyHorst** [micro/go-micro#66]
I'm playing with the examples at the moment.

If i run the pubsub example with the consul(default) backend everything works as expected.

```
 ~/go-micro/examples/pubsub (git)-[master] % go run main.go                               
2016/03/22 17:59:21 Broker Listening on [::]:34344
[sub] received message: 0: 2016-03-22 17:59:22.244760259 +0100 CET header map[id:0]
[pub] pubbed message: 0: 2016-03-22 17:59:22.244760259 +0100 CET
[sub] received message: 1: 2016-03-22 17:59:23.244835525 +0100 CET header map[id:1]
[pub] pubbed message: 1: 2016-03-22 17:59:23.244835525 +0100 CET
[sub] received message: 2: 2016-03-22 17:59:24.244759704 +0100 CET header map[id:2]
[pub] pubbed message: 2: 2016-03-22 17:59:24.244759704 +0100 CET
[sub] received message: 3: 2016-03-22 17:59:25.244865275 +0100 CET header map[id:3]
[pub] pubbed message: 3: 2016-03-22 17:59:25.244865275 +0100 CET
[sub] received message: 4: 2016-03-22 17:59:26.24476599 +0100 CET header map[id:4]
```

but if i import **_ "github.com/micro/go-plugins/registry/etcd"** and try to run the example
the process panics with:

```
~/go-micro/examples/pubsub (git)-[master] % go run main.go --registry etcd --registry_address http://127.0.0.1:4001
panic: http: multiple registrations for /_sub

goroutine 1 [running]:
panic(0x9d9b40, 0xc82014a080)
    /usr/lib/go/src/runtime/panic.go:464 +0x3e6
net/http.(*ServeMux).Handle(0xc820012ba0, 0xc548e0, 0x5, 0x7f97413972a0, 0xc8200cc160)
    /usr/lib/go/src/net/http/server.go:1926 +0x297
net/http.Handle(0xc548e0, 0x5, 0x7f97413972a0, 0xc8200cc160)
    /usr/lib/go/src/net/http/server.go:1961 +0x4b
github.com/micro/go-micro/broker.(*httpBroker).Init(0xc8200cc160, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/rkaufmann/.go/src/github.com/micro/go-micro/broker/http_broker.go:321 +0x30f
github.com/micro/go-micro/broker.Init(0x0, 0x0, 0x0, 0x0, 0x0)
    /home/rkaufmann/.go/src/github.com/micro/go-micro/broker/broker.go:49 +0x55
main.main()
    /home/rkaufmann/go-micro/examples/pubsub/main.go:49 +0x5b
exit status 2
```

am i doing something wrong ?

**Comment by asim** [comment]
Thanks for raising the issue. The sub handler was being re-registered when the broker was reinitialised. Fixed in this commit. https://github.com/micro/go-micro/commit/97860a04885951642271e41e6ad012bc580ee328

**Comment by HeavyHorst** [comment]
works now. thanks for the quick reply !
