### ISSUE TITLE
panic: Header called after Handler finished

### ISSUE THREAD

**Issue by xxw-santi** [micro/go-micro#749]
```
**server code**

	service := micro.NewService(
		micro.Name(configure.SERVER_NAME),
		micro.Version("latest"),
		micro.Address(configure.HOST),
		//micro.WrapHandler(AuthWrapper),
	)
	service.Init()
	protos.RegisterSendMessageServiceHandler(service.Server(), handle.NewService())
	protos.RegisterAuthHandler(service.Server(), handle.NewAuthService())

	if err := service.Run(); err != nil {
		log.Fatal(err)
	}


**question descirbe**
it can run in go client, but when i change python or php as client,   server will be shuttle down, but all processes have been implemented,   and no response has been received.


**serve run info**
$ go run message_server.go --registry=consul
2019/09/10 15:28:32 Transport [http] Listening on 127.0.0.1:8881
2019/09/10 15:28:32 Broker [http] Connected to [::]:50335
2019/09/10 15:28:32 Registry [consul] Registering node: srv.wechat.message-f9e6a                                                                                                                                                                                               937-04f3-46f0-921f-94ed3acc9efc

**error**
panic: Header called after Handler finished

goroutine 14 [running]:
golang.org/x/net/http2.(*responseWriter).Header(0xc000006008, 0xc00029afc0)
        D:/go/pkg/mod/golang.org/x/net@v0.0.0-20190724013045-ca1201d0de80/http2/                                                                                                                                                                                               server.go:2564 +0xa0
github.com/micro/go-micro/transport.(*httpTransportSocket).Send(0xc0001321e0, 0x                                                                                                                                                                                               c000004920, 0x0, 0x0)
        D:/go/pkg/mod/github.com/micro/go-micro@v1.9.1/transport/http_transport.                                                                                                                                                                                               go:297 +0x509
github.com/micro/go-micro/server.(*rpcServer).ServeConn.func2(0xc00002c4a0, 0xc0                                                                                                                                                                                               00100f60, 0x11e9ce0, 0xc0001321e0, 0x0, 0x0, 0xc00028c080)
        D:/go/pkg/mod/github.com/micro/go-micro@v1.9.1/server/rpc_server.go:153                                                                                                                                                                                                +0xb6
created by github.com/micro/go-micro/server.(*rpcServer).ServeConn
        D:/go/pkg/mod/github.com/micro/go-micro@v1.9.1/server/rpc_server.go:138                                                                                                                                                                                                +0x538
exit status 2

```

**Comment by milosgajdos** [comment]
I'm not sure you should be registering two different handlers in one service. I'm not exactly sure what the behaviour is like when you do that. In practice, your service should be simple and be doing only one thing hence it should have only one handler.

**Comment by asim** [comment]
This is unrelated to having two handlers registered in one service. You can register as many as you want.

The issue was that in the http2 request path we can write the response after the handler has exited. I've now added a read lock in the server transport that should prevent the socket from being closed before the data has been written.

**Comment by milosgajdos** [comment]
Cool. Like I said I was not sure. Good to hear you found what the problem was.
Can you link the PR to this issue, so it's closed automatically once the bug fix is merged in?

**Comment by asim** [comment]
Fix https://github.com/micro/go-micro/commit/6ec32805d013ec219796b2c5c25186372b0b20c1
