### ISSUE TITLE
cannot use auth.callOpts (type []"...github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []".../go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable

### ISSUE THREAD

**Issue by itcreator** [micro/go-micro#992]
Looks like go-micro  uses _deprecated version_ of **coreos/etcd/clientv3**
message:
```
vendor/github.com/coreos/etcd/clientv3/auth.go:166:106: too many errors
# project/vendor/github.com/coreos/etcd/clientv3
vendor/github.com/coreos/etcd/clientv3/auth.go:121:72: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
vendor/github.com/coreos/etcd/clientv3/auth.go:126:74: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
vendor/github.com/coreos/etcd/clientv3/auth.go:131:152: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
vendor/github.com/coreos/etcd/clientv3/auth.go:136:144: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
vendor/github.com/coreos/etcd/clientv3/auth.go:141:86: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
vendor/github.com/coreos/etcd/clientv3/auth.go:146:122: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
vendor/github.com/coreos/etcd/clientv3/auth.go:151:104: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
vendor/github.com/coreos/etcd/clientv3/auth.go:156:80: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
vendor/github.com/coreos/etcd/clientv3/auth.go:161:72: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
vendor/github.com/coreos/etcd/clientv3/auth.go:166:106: cannot use auth.callOpts (type []"project/vendor/github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"project/vendor/go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
vendor/github.com/coreos/etcd/clientv3/auth.go:166:106: too many errors
```
according  **coreos/etcd/clientv3** installation guide it should include **go.etcd.io** instead of **github.com/coreos/etcd/**

![image](https://user-images.githubusercontent.com/928509/69664584-b622dc00-1099-11ea-8fb1-e7481b1e1598.png)

when I try to change it it returns such error
```
panic: /debug/requests is already registered. You may have two independent copies of golang.org/x/net/trace in your binary, trying to maintain separate state. This may involve a vendored copy of golang.org/x/net/trace.

goroutine 1 [running]:
project/vendor/go.etcd.io/etcd/vendor/golang.org/x/net/trace.init.0()
        /go/src/project/vendor/go.etcd.io/etcd/vendor/golang.org/x/net/trace/trace.go:123 +0x1cd
exit status 2
```

**Comment by itcreator** [comment]
looks like it related to https://github.com/etcd-io/etcd/pull/10044#issuecomment-417125341

**Comment by asim** [comment]
export GO111MODULE=on

go get github.com/micro/micro

**Comment by itcreator** [comment]
Thank you @asim 
switching from glide to go modules solved this issue

**Comment by Vakishna** [comment]
> export GO111MODULE=on
> 
> go get github.com/micro/micro

Thanks, this works

**Comment by fjfo** [comment]
> export GO111MODULE=on
> 
> go get github.com/micro/micro

Great
